data:
  registries.conf: |
    registries:
      - name: ecr
        api_url: https://327426387577.dkr.ecr.ap-northeast-2.amazonaws.com/scas-frontend:4595f476a397d2a224130f528a814de94366ee8a
        prefix: 327426387577.dkr.ecr.ap-northeast-2.amazonaws.com/scas-frontend:4595f476a397d2a224130f528a814de94366ee8a
        credentials: ext:/usr/local/bin/argocd-ecr-login

