apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # 이 앱의 이름은 root 입니다.
  name: root
  namespace: argocd
spec:
  project: default
  source:
    # 이 root 앱은 자기 자신이 있는 리포지토리를 바라봅니다.
    repoURL: 'https://github.com/leeejjju/scas-manifests.git'
    targetRevision: main
    # ⭐️ 그리고 apps/ 폴더 안의 모든 것을 감시합니다! ⭐️
    path: apps
  destination:
    # Application 리소스들은 argocd 네임스페이스에 생성되어야 합니다.
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  # 이 root 앱은 절대적으로 Git을 신뢰하고 자동으로 동기화합니다.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
