apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: ecr
        api_url: https://327426387577.dkr.ecr.ap-northeast-2.amazonaws.com
        prefix: 327426387577.dkr.ecr.ap-northeast-2.amazonaws.com
        credentials: ext:/usr/local/bin/argocd-ecr-login

